name: friendly_sports
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  git: ^2.3.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.14.0
  table_calendar: ^3.1.3
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
