// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpPeMPMsIoJm1eAZwFbQ5xpqpgjLYLeg',
    appId: '1:223310027624:web:c9ad5030d496698ae494dd',
    messagingSenderId: '223310027624',
    projectId: 'friendlysportsp2',
    authDomain: 'friendlysportsp2.firebaseapp.com',
    storageBucket: 'friendlysportsp2.firebasestorage.app',
    measurementId: 'G-5Y27DPM5ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdsJSQ91CQSzFRogRiplW3hQrRBGYUmj8',
    appId: '1:223310027624:android:d4a274d55c6a742be494dd',
    messagingSenderId: '223310027624',
    projectId: 'friendlysportsp2',
    storageBucket: 'friendlysportsp2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCm6w3-S8mM4oQU0WxOB_LpFAR3Rr0fls',
    appId: '1:223310027624:ios:2991ca6d66f62b12e494dd',
    messagingSenderId: '223310027624',
    projectId: 'friendlysportsp2',
    storageBucket: 'friendlysportsp2.firebasestorage.app',
    iosBundleId: 'com.example.friendlySports',
  );
}
